- project:
    check:
      jobs:
        - linters:
            vars:
              linters:
                - coala
    gate:
      jobs:
        - linters:
            vars:
              linters:
                - coala

    release:
      jobs:
        - upload-pypi-sesheta

    kebechet-auto-gate:
      jobs:
        - linters:
            vars:
              linters:
                - coala
