---
  - name: login to OpenShift using provided token
    command: "oc login {{ OCP_URL }} --insecure-skip-tls-verify=true --token {{ OCP_TOKEN }}"
    changed_when: False

  - name: "make sure to use project {{ KEBECHET_INFRA_NAMESPACE }}"
    command: "oc project {{ KEBECHET_INFRA_NAMESPACE }}"
    register: project_exists
    ignore_errors: true

  - name: importing required Fedora ImageStreamTags from upstream Registries
    command: "oc tag --namespace {{ KEBECHET_INFRA_NAMESPACE }} registry.fedoraproject.org/fedora:{{ item }} fedora:{{ item }}"
    with_items:
      - 28

  - name: create ImageStream
    command: oc create --namespace {{ KEBECHET_INFRA_NAMESPACE  }}  --filename=../openshift/imageStream-template.yaml
    ignore_errors: true

  - name: create BuildConfig
    command: oc create --namespace {{ KEBECHET_INFRA_NAMESPACE  }}  --filename ../openshift/buildConfig-template.yaml
    ignore_errors: true

  - name: create CronJob
    command: oc create --namespace {{ KEBECHET_INFRA_NAMESPACE  }}  --filename ../openshift/cronJob-template.yaml
    ignore_errors: true
